export const SHOW_DRAWER = 'SHOW_DRAWER'
export const SET_SEARCH = 'SET_SEARCH'
export const SET_SORT = 'SET_SORT'
export const SET_FILTER = 'SET_FILTER'
export const SET_COUNT_BASKET = 'SET_COUNT_BASKET'
export const SET_IS_MOBILE_APP = 'SET_IS_MOBILE_APP'
export const SHOW_LOAD = 'SHOW_LOAD'
